global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
global using Microsoft.Extensions.Configuration;
global using System.ComponentModel.DataAnnotations;
global using System.Data;
global using System.Data.SqlClient;
global using System.IO;
global using System.Linq;
global using System.Collections.Generic;
global using PB.Core;
global using System;
global using System.Globalization;
global using static PB.Core.Response;
global using Microsoft.CodeAnalysis;
global using MailKit.Net.Smtp;
global using MailKit;
global using MimeKit;