namespace PB.Infrastructure
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ApplicationDbContext ctx)
        {
            if (ctx.Universities.Count() != 0 || ctx.Educations.Count() != 0) return;

            ctx.Universities.Add(new University { Name = "IT-Universitet i København", Id = "ITU" });
            ctx.Universities.Add(new University { Name = "Copenhagen Business School", Id = "CBS" });
            ctx.Universities.Add(new University { Name = "Københavns Universitet", Id = "KU" });
            ctx.Universities.Add(new University { Name = "Syddansk Universitet", Id = "SDU" });

            ctx.Educations.Add(new Education { Name = "Klinisk sygepleje (kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Veterinærmedicin", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - International Business", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Skov- og landskabsingeniørvirksomhed", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Medievidenskab (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Miljøteknologi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Politisk Kommunikation og Ledelse", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Business Administration and Data Science", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Integrerede fødevarestudier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi-erhvervssprog (negot) i international turisme og fritidsmanagement", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "International virksomhedskommunikation - Tysk", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Retorik", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Biomedicinsk informatik", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Business Administration and Information Systems", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Husdyrvidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Software Engineering", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Film- og medievidenskab", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "HA i projektledelse", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Idræt og fysisk aktivitet", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Geografi og geoinformatik", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Datalogi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Strategy, Organisation and Leadership", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Oldtidskundskab", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Social datavidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Interreligiøse islamstudier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Datalogi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Økonomi (cand.oecon. med profil i finansiering)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Europas religiøse rødder", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Skovbrugsvidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Idræt og Sundhed (kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Business Administration and Ebusiness", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Medicin / Lægevidenskab (3-årig kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Engelsk (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "HA(jur.)", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Designledelse", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Økonomisk Markedsføring", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Sales Management", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Odontologi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Mellemøstens sprog og samfund (ægyptologi)", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Informationsvidenskab, it og interaktionsdesign", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "European Studies", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Strategy and Organization", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Folkesundhedsvidenskab", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Biologi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i spiludvikling og læringsteknologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Historie", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Musikvidenskab", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Software Development and Technology", Grade = "Kandidat", University = ctx.Universities.Find("ITU") });
            ctx.Educations.Add(new Education { Name = "Business Administration and Bioentrepreneurship", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Samfundsfag", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi og Virksomhedskommunikation", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i Mechatronics", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Management of Innovation and Business Development", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Indianske sprog og kulturer", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Jura", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Kunsthistorie", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Naturforvaltning", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Assyriologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i robotteknologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Forsikringsmatematik", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Medicinalkemi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Økonomi (oecon.)", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Journalistik (cand.mag.)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Mellemøstens sprog og samfund", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Sundhedsfaglig kandidatuddannelse", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Økonomi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Journalistik", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Agronomi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Bioteknologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Audiologopædi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi og Psykologi", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Forsikringsmatematik", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Ægyptologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Interkulturelle markedsstudier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - People and Business Development", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Audiologopædi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Tysk sprog og kultur", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Medicin", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Business Administration & Sociology", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Klinisk biomekanik", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi-erhvervssprog (negot) - engelsk eller tysk (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "HA(mat.)", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Klinisk biomekanik", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Statskundskab", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Humanbiologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Immunologi og inflammation", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Product Development and Innovation", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Biokemi og molekylær biologi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Klassisk græsk", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i bygningsteknik", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Fysik", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Italiensk sprog og kultur", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "International Business and Politics", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Klassiske studier: Oldtidskundskab (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Matematik-økonomi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Fysik", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Kognition og kommunikation", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Italiensk sprog og kultur", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Litteraturvidenskab", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Business Controlling", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Dansk", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Biokemi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - International Marketing and Management", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Engelsk", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.soc. i jura", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Litteraturvidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Sundheds- og velfærdsteknologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Tværkulturelle studier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "HA i markeds- og kulturanalyse", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Finansiering og Regnskab", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Brand Management and Marketing Communication", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Samfundsfag", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Biomedicin", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Accounting and Finance", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Jura", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Psykologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "International Security and Law", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Medicin", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Asienstudier (koreastudier)", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Energiteknologi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Organisational Innovation and Entrepreneurship (cand.soc.)", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Teater- og performancestudier", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Stem-undervisning", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Journalistik (cand.public.)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Teater- og performancestudier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Brand and Communications Management", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Engineering, Innovation and Business", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "European Master in Tourism Management", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Operations Management", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "International virksomhedskommunikation - Engelsk", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Fødevarevidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Pædagogik", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Sports and Event Management", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Farmaci", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Revisorkandidat", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Global Business Informatics", Grade = "Bachelor", University = ctx.Universities.Find("ITU") });
            ctx.Educations.Add(new Education { Name = "HA(kom.)", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Forhistorisk arkæologi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Fysioterapi (kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Naturressourcer og udvikling", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Maskinteknik", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "HA(fil.)", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Digital Innovation & Management", Grade = "Kandidat", University = ctx.Universities.Find("ITU") });
            ctx.Educations.Add(new Education { Name = "Statskundskab", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Forhistorisk arkæologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Farmaci (kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi og jura, HA (jur.)", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Kultur og formidling (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Digital Design and Interactive Technologies", Grade = "Bachelor", University = ctx.Universities.Find("ITU") });
            ctx.Educations.Add(new Education { Name = "Historie (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Global Marketing and Consumer Culture", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Engelsk", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Audiologi (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Lægemiddelvidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Humanistisk-samfundsvidenskabelig idrætsvidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Folkesundhedsvidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Konstruktionsteknik", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "International Business", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Machine learning og datavidenskab", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Matematik-økonomi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i Maskinteknik", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc.jur. (Erhvervsjura)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand. it. - Web Communication Design", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Filosofi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Historie", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Psykologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Market and Management Anthropology", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "HA(psyk.)", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Business Administration and Innovation in Health Care", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Farmaci", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Filosofi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Kommunikation og it", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Datalogi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Amerikanske studier", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Østeuropastudier", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Litteraturvidenskab (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Sundheds- og Velfærdsteknologi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cultural Sociology", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Datalogi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "International Business & Politics", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Østeuropastudier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Marketing, Social Media, and Digitalization", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Klassisk arkæologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Latin", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Business, Language and Culture - Business and Development Studies", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Organisational Innovation and Entrepreneurship - Strategic Design and Entrepreneurship (cand.soc.)", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Fødevareinnovation og sundhed", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Landskabsarkitektur", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Miljøvidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Veterinærmedicin", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Antropologi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Religionsstudier (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Grønlandske og arktiske studier", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "International erhvervsøkonomi med fremmedsprog (BA int.)", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Asienstudier (kinastudier)", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Lingvistik", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Kemi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Antropologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Folkesundhedsvidenskab", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Biologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i bygningsteknik", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Kemi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Media Technology and Games", Grade = "Kandidat", University = ctx.Universities.Find("ITU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Mechatronics", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Retorik", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Historie", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Management Accounting", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Asienstudier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i produktion", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Software Engineering", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. International Business and Management", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Film- og medievidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Miljø- og naturressourceøkonomi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Medicinalkemi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Business Administration & Service Management", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Robotteknologi (Avanceret robotteknologi/Droner og autonome systemer)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Migrationsstudier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "International Business in Asia - Chinese", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Matematik", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i robotteknologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Human Resource Management", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Audiologopædi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Humanfysiologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Husdyrvidenskab", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Amerikanske studier (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Odontologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Matematik", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Medievidenskab", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand. it. - Product Design", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Geografi og geoinformatik", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Audiologopædi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Sprogpsykologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Spansk sprog og kultur", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Audiologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Fysik og Teknologi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Spansk sprog og kultur", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Asienstudier (japanstudier)", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Sociologi og kulturanalyse", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Neuroscience", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Biologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Interkulturel pædagogik og dansk som andetsprog", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Jordbrugsøkonomi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i softwareteknologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Informationsvidenskab og kulturformidling", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Moderne kultur", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "HA(it.)", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Musikvidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Dansk (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Sundhed og informatik", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Afrikastudier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Kunsthistorie", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Pædagogik (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Human ernæring", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Litteraturvidenskab", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Filosofi (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Dansk", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Matematik og Anvendt matematik", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Business, Language and Culture - Diversity and Change Management", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Psykologi (kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "International Virksomhedskommunikation (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Fransk sprog og kultur", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Nærorientalsk arkæologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Mellemøstens sprog og samfund (nærorientalsk ark.)", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Entreprenørskab og ledelse", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Samfundsfag", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Informationsstudier", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Tysk (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. International Business and Marketing", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Jura", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc.int., Sønderborg", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Fransk sprog og kultur", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Sociologi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Ergoterapi (kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Geologi - geoscience", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Cand.it. - Webkommunikation", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Medicinalkemi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Folkesundhedsvidenskab (kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Mellemøstens sprog og samfund", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Religionsvidenskab", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Tandplejeruddannelsen", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i kemi- og bioteknologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Bioteknologi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Religionsvidenskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Professionsbachelor i engelsk og digital markedskommunikation", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Business, Language & Culture", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Klinisk ernæring", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Molekylær biomedicin", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "HA almen", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Sikkerheds- og risikoledelse", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Tysk sprog og kultur", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Data Science", Grade = "Bachelor", University = ctx.Universities.Find("ITU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Spiludvikling og læringsteknologi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Moderne indien og sydasienstudier", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Teologi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Management of Creative Business Processes (cand.soc.)", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Electronics", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Interkulturelle markedsstudier", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i integreret design", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Naturressourcer", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Anvendt matematik", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Datalogi-økonomi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Statskundskab", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Teologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Sundhedsfaglig kandidatuddannelse (kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Dansk", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Biokemi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Product Development and Innovation", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Electronics", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Grønlandske og arktiske studier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Global udvikling", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi-erhvervssprog (negot)", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i Electronics", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Nanoscience", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Samfundsfag", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Matematik-økonomi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Jordemodervidenskab (kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Mechatronics", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i kemi og bioteknologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Jura", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Filosofi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Miljø- og fødevareøkonomi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Public Management and Social Development (cand.soc.)", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Human Resource Management", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i Global Management and Manufacturing", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "International virksomhedskommunikation - 2 fremmedsprog", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Farmaci", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Computer Science", Grade = "Kandidat", University = ctx.Universities.Find("ITU") });
            ctx.Educations.Add(new Education { Name = "Fødevarer og ernæring", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Europæisk etnologi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Designkultur og økonomi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Finance and Investments", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Biomedicin", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Comparative Public Policy and Welfare Studies", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Supply Chain Management", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Applied Economics and Finance", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Europæisk etnologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Innovation and Business", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Medicin", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Accounting, Strategy and Control", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Styring og Ledelse", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Mellemøstens sprog og samfund (assyriologi)", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Innovation and Business Development", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Nanoscience", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Statskundskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "It og kognition", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Digital Design and Interactive Technologies", Grade = "Kandidat", University = ctx.Universities.Find("ITU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc.aud. (Revisor)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Statistik", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Kemi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi, HA", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Fysik", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Pædagogik", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "HA i europæisk business", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi og Jura", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Kemi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Designstudier", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Matematik-økonomi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Fysik", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i energiteknologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Økonomi (cand.oecon.)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Kommunikation og it", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Engelsk", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Økonomi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Global sundhed", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Religionsstudier", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Sundhed og informatik", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Bioinformatik", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Klimaforandringer", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Farmaceutisk videnskab", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i fysik og teknologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Advanced Economics and Finance (cand.oecon.)", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Civilingeniør i Kemi og bioteknologi (kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Psykologi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Environmental and Resource Management", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Idræt og sundhed", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Portugisiske og brasilianske studier", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Fødevarevidenskab/mejeriingeniør", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Bibliotekskundskab og videnskommunikation", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Matematik", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi - Finance and Strategic Management", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Software Development", Grade = "Bachelor", University = ctx.Universities.Find("ITU") });
            ctx.Educations.Add(new Education { Name = "Tysk", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Erhvervsøkonomi og Matematik", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Sociologi", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Business Administration & Digital Management", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Geologi - geoscience", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Visuel kultur", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Biokemi og molekylær biologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Lingvistik", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Klassisk arkæologi", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Latin", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Designkultur", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Forretnings- & Markedsudvikling", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i elektrisk energiteknologi", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Data Science", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "International Business in Asia - Japanese", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Biologi", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Molekylær biomedicin", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "International Shipping & Trade", Grade = "Bachelor", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Business Administration and Philosophy", Grade = "Kandidat", University = ctx.Universities.Find("CBS") });
            ctx.Educations.Add(new Education { Name = "Anvendt kulturanalyse", Grade = "Kandidat", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Cand.merc. Market Anthropology", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Diplomingeniør i elektronik", Grade = "Bachelor", University = ctx.Universities.Find("SDU") });
            ctx.Educations.Add(new Education { Name = "Landskabsarkitektur", Grade = "Bachelor", University = ctx.Universities.Find("KU") });
            ctx.Educations.Add(new Education { Name = "Mellemøststudier (Kandidat)", Grade = "Kandidat", University = ctx.Universities.Find("SDU") });

            ctx.SaveChanges();
        }
    }
}
