namespace PB.Infrastructure
{
    public static class ModelBuilderExtensions
    {
        public static void Seed(this ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<University>().HasData(
                    new University { Name = "IT-Universitet i København", Id = "ITU" },
                    new University { Name = "Copenhagen Business School", Id = "CBS" },
                    new University { Name = "Universitet", Id = "Uni abbrv" },
                    new University { Name = "Københavns Universitet", Id = "KU" },
                    new University { Name = "Syddansk Universitet", Id = "SDU" }
                );

            modelBuilder.Entity<Education>().HasData(
                    new Education { Name = "Tysk", Grade = "Bachelor", UniversityID = "SDU", Id = 1 },
                    new Education { Name = "Skovbrugsvidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 2 },
                    new Education { Name = "Kemi", Grade = "Kandidat", UniversityID = "SDU", Id = 3 },
                    new Education { Name = "Asienstudier (koreastudier)", Grade = "Bachelor", UniversityID = "KU", Id = 4 },
                    new Education { Name = "Teologi", Grade = "Kandidat", UniversityID = "KU", Id = 5 },
                    new Education { Name = "Interkulturelle markedsstudier", Grade = "Kandidat", UniversityID = "CBS", Id = 6 },
                    new Education { Name = "Folkesundhedsvidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 7 },
                    new Education { Name = "Biokemi", Grade = "Kandidat", UniversityID = "KU", Id = 8 },
                    new Education { Name = "Cand.it. - Webkommunikation", Grade = "Kandidat", UniversityID = "SDU", Id = 9 },
                    new Education { Name = "Biokemi og molekylær biologi", Grade = "Kandidat", UniversityID = "SDU", Id = 10 },
                    new Education { Name = "Audiologopædi", Grade = "Bachelor", UniversityID = "SDU", Id = 11 },
                    new Education { Name = "Business Administration and Bioentrepreneurship", Grade = "Kandidat", UniversityID = "CBS", Id = 12 },
                    new Education { Name = "Erhvervsøkonomi og Jura", Grade = "Kandidat", UniversityID = "CBS", Id = 13 },
                    new Education { Name = "Matematik-økonomi", Grade = "Bachelor", UniversityID = "KU", Id = 14 },
                    new Education { Name = "Organisational Innovation and Entrepreneurship - Strategic Design and Entrepreneurship (cand.soc.)", Grade = "Kandidat", UniversityID = "CBS", Id = 15 },
                    new Education { Name = "Tysk sprog og kultur", Grade = "Bachelor", UniversityID = "KU", Id = 16 },
                    new Education { Name = "Medicinalkemi", Grade = "Kandidat", UniversityID = "SDU", Id = 17 },
                    new Education { Name = "Engelsk (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 18 },
                    new Education { Name = "Mellemøstens sprog og samfund (ægyptologi)", Grade = "Bachelor", UniversityID = "KU", Id = 19 },
                    new Education { Name = "Spansk sprog og kultur", Grade = "Bachelor", UniversityID = "KU", Id = 20 },
                    new Education { Name = "Kemi", Grade = "Bachelor", UniversityID = "SDU", Id = 21 },
                    new Education { Name = "Engelsk", Grade = "Bachelor", UniversityID = "SDU", Id = 22 },
                    new Education { Name = "Comparative Public Policy and Welfare Studies", Grade = "Kandidat", UniversityID = "SDU", Id = 23 },
                    new Education { Name = "Klinisk biomekanik", Grade = "Kandidat", UniversityID = "SDU", Id = 24 },
                    new Education { Name = "Statistik", Grade = "Kandidat", UniversityID = "KU", Id = 25 },
                    new Education { Name = "Folkesundhedsvidenskab", Grade = "Bachelor", UniversityID = "KU", Id = 26 },
                    new Education { Name = "Anvendt kulturanalyse", Grade = "Kandidat", UniversityID = "KU", Id = 27 },
                    new Education { Name = "Visuel kultur", Grade = "Kandidat", UniversityID = "KU", Id = 28 },
                    new Education { Name = "Civilingeniør i energiteknologi", Grade = "Bachelor", UniversityID = "SDU", Id = 29 },
                    new Education { Name = "Business Administration & Service Management", Grade = "Bachelor", UniversityID = "CBS", Id = 30 },
                    new Education { Name = "Interkulturel pædagogik og dansk som andetsprog", Grade = "Bachelor", UniversityID = "SDU", Id = 31 },
                    new Education { Name = "Erhvervsøkonomi - Finance and Investments", Grade = "Kandidat", UniversityID = "CBS", Id = 32 },
                    new Education { Name = "Humanbiologi", Grade = "Kandidat", UniversityID = "KU", Id = 33 },
                    new Education { Name = "Psykologi", Grade = "Bachelor", UniversityID = "SDU", Id = 34 },
                    new Education { Name = "Medievidenskab (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 35 },
                    new Education { Name = "Politisk Kommunikation og Ledelse", Grade = "Kandidat", UniversityID = "CBS", Id = 36 },
                    new Education { Name = "Biokemi", Grade = "Bachelor", UniversityID = "KU", Id = 37 },
                    new Education { Name = "International Business and Politics", Grade = "Kandidat", UniversityID = "CBS", Id = 38 },
                    new Education { Name = "Teater- og performancestudier", Grade = "Bachelor", UniversityID = "KU", Id = 39 },
                    new Education { Name = "Cand. it. - Web Communication Design", Grade = "Kandidat", UniversityID = "SDU", Id = 40 },
                    new Education { Name = "Nanoscience", Grade = "Kandidat", UniversityID = "KU", Id = 41 },
                    new Education { Name = "Revisorkandidat", Grade = "Kandidat", UniversityID = "CBS", Id = 42 },
                    new Education { Name = "Fødevarevidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 43 },
                    new Education { Name = "Geografi og geoinformatik", Grade = "Kandidat", UniversityID = "KU", Id = 44 },
                    new Education { Name = "Engelsk", Grade = "Kandidat", UniversityID = "KU", Id = 45 },
                    new Education { Name = "Informationsvidenskab, it og interaktionsdesign", Grade = "Bachelor", UniversityID = "SDU", Id = 46 },
                    new Education { Name = "Medicin / Lægevidenskab (3-årig kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 47 },
                    new Education { Name = "Erhvervsøkonomi - Brand and Communications Management", Grade = "Kandidat", UniversityID = "CBS", Id = 48 },
                    new Education { Name = "Public Management and Social Development (cand.soc.)", Grade = "Kandidat", UniversityID = "CBS", Id = 49 },
                    new Education { Name = "Humanistisk-samfundsvidenskabelig idrætsvidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 50 },
                    new Education { Name = "Civilingeniør i Product Development and Innovation", Grade = "Bachelor", UniversityID = "SDU", Id = 51 },
                    new Education { Name = "Mellemøstens sprog og samfund", Grade = "Kandidat", UniversityID = "KU", Id = 52 },
                    new Education { Name = "Data Science", Grade = "Kandidat", UniversityID = "SDU", Id = 53 },
                    new Education { Name = "International Business & Politics", Grade = "Bachelor", UniversityID = "CBS", Id = 54 },
                    new Education { Name = "Civilingeniør i Electronics", Grade = "Bachelor", UniversityID = "SDU", Id = 55 },
                    new Education { Name = "Klinisk biomekanik", Grade = "Bachelor", UniversityID = "SDU", Id = 56 },
                    new Education { Name = "Diplomingeniør i elektrisk energiteknologi", Grade = "Bachelor", UniversityID = "SDU", Id = 57 },
                    new Education { Name = "Film- og medievidenskab", Grade = "Bachelor", UniversityID = "KU", Id = 58 },
                    new Education { Name = "Psykologi", Grade = "Kandidat", UniversityID = "KU", Id = 59 },
                    new Education { Name = "Idræt og Sundhed (kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 60 },
                    new Education { Name = "Business, Language and Culture - Business and Development Studies", Grade = "Kandidat", UniversityID = "CBS", Id = 61 },
                    new Education { Name = "Diplomingeniør i produktion", Grade = "Bachelor", UniversityID = "SDU", Id = 62 },
                    new Education { Name = "Designstudier", Grade = "Kandidat", UniversityID = "SDU", Id = 63 },
                    new Education { Name = "Veterinærmedicin", Grade = "Kandidat", UniversityID = "KU", Id = 64 },
                    new Education { Name = "Amerikanske studier (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 65 },
                    new Education { Name = "Kommunikation og it", Grade = "Kandidat", UniversityID = "KU", Id = 66 },
                    new Education { Name = "Erhvervsøkonomi - International Business", Grade = "Kandidat", UniversityID = "CBS", Id = 67 },
                    new Education { Name = "Økonomi (cand.oecon. med profil i finansiering)", Grade = "Kandidat", UniversityID = "SDU", Id = 68 },
                    new Education { Name = "HA(mat.)", Grade = "Bachelor", UniversityID = "CBS", Id = 69 },
                    new Education { Name = "Fransk sprog og kultur", Grade = "Bachelor", UniversityID = "KU", Id = 70 },
                    new Education { Name = "Media Technology and Games", Grade = "Kandidat", UniversityID = "ITU", Id = 71 },
                    new Education { Name = "Matematik-økonomi", Grade = "Kandidat", UniversityID = "SDU", Id = 72 },
                    new Education { Name = "Professionsbachelor i engelsk og digital markedskommunikation", Grade = "Bachelor", UniversityID = "SDU", Id = 73 },
                    new Education { Name = "Nanoscience", Grade = "Bachelor", UniversityID = "KU", Id = 74 },
                    new Education { Name = "Lingvistik", Grade = "Kandidat", UniversityID = "KU", Id = 75 },
                    new Education { Name = "Erhvervsøkonomi - Strategy, Organisation and Leadership", Grade = "Kandidat", UniversityID = "CBS", Id = 76 },
                    new Education { Name = "International Virksomhedskommunikation (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 77 },
                    new Education { Name = "Medicin", Grade = "Kandidat", UniversityID = "KU", Id = 78 },
                    new Education { Name = "Asienstudier (japanstudier)", Grade = "Bachelor", UniversityID = "KU", Id = 79 },
                    new Education { Name = "Erhvervsøkonomi og Matematik", Grade = "Kandidat", UniversityID = "CBS", Id = 80 },
                    new Education { Name = "Cand.merc. Market Anthropology", Grade = "Kandidat", UniversityID = "SDU", Id = 81 },
                    new Education { Name = "Cand.merc. Innovation and Business Development", Grade = "Kandidat", UniversityID = "SDU", Id = 82 }, new Education { Name = "Cand.merc. Marketing, Social Media, and Digitalization", Grade = "Kandidat", UniversityID = "SDU", Id = 83 },
                    new Education { Name = "Civilingeniør i Fysik og Teknologi", Grade = "Kandidat", UniversityID = "SDU", Id = 84 },
                    new Education { Name = "HA(fil.)", Grade = "Bachelor", UniversityID = "CBS", Id = 85 },
                    new Education { Name = "Anvendt matematik", Grade = "Kandidat", UniversityID = "SDU", Id = 86 },
                    new Education { Name = "Latin", Grade = "Kandidat", UniversityID = "KU", Id = 87 },
                    new Education { Name = "Business, Language and Culture - Diversity and Change Management", Grade = "Kandidat", UniversityID = "CBS", Id = 88 },
                    new Education { Name = "Market and Management Anthropology", Grade = "Bachelor", UniversityID = "SDU", Id = 89 },
                    new Education { Name = "Miljø- og naturressourceøkonomi", Grade = "Kandidat", UniversityID = "KU", Id = 90 },
                    new Education { Name = "Cultural Sociology", Grade = "Kandidat", UniversityID = "SDU", Id = 91 },
                    new Education { Name = "Civilingeniør i Engineering, Innovation and Business", Grade = "Kandidat", UniversityID = "SDU", Id = 92 },
                    new Education { Name = "Biologi", Grade = "Kandidat", UniversityID = "SDU", Id = 93 },
                    new Education { Name = "Software Development and Technology", Grade = "Kandidat", UniversityID = "ITU", Id = 94 },
                    new Education { Name = "Litteraturvidenskab", Grade = "Bachelor", UniversityID = "SDU", Id = 95 },
                    new Education { Name = "Statskundskab", Grade = "Kandidat", UniversityID = "KU", Id = 96 },
                    new Education { Name = "Social datavidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 97 },
                    new Education { Name = "Business Administration and Data Science", Grade = "Kandidat", UniversityID = "CBS", Id = 98 },
                    new Education { Name = "Veterinærmedicin", Grade = "Bachelor", UniversityID = "KU", Id = 99 },
                    new Education { Name = "Civilingeniør i bygningsteknik", Grade = "Bachelor", UniversityID = "SDU", Id = 100 },
                    new Education { Name = "Diplomingeniør i integreret design", Grade = "Bachelor", UniversityID = "SDU", Id = 101 },
                    new Education { Name = "Farmaci (kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 102 },
                    new Education { Name = "Erhvervsøkonomi - Applied Economics and Finance", Grade = "Kandidat", UniversityID = "CBS", Id = 103 },
                    new Education { Name = "Matematik-økonomi", Grade = "Bachelor", UniversityID = "SDU", Id = 104 },
                    new Education { Name = "Italiensk sprog og kultur", Grade = "Kandidat", UniversityID = "KU", Id = 105 },
                    new Education { Name = "HA i projektledelse", Grade = "Bachelor", UniversityID = "CBS", Id = 106 },
                    new Education { Name = "Civilingeniør i Energiteknologi", Grade = "Kandidat", UniversityID = "SDU", Id = 107 },
                    new Education { Name = "HA(kom.)", Grade = "Bachelor", UniversityID = "CBS", Id = 108 },
                    new Education { Name = "Diplomingeniør i Global Management and Manufacturing", Grade = "Bachelor", UniversityID = "SDU", Id = 109 },
                    new Education { Name = "Tværkulturelle studier", Grade = "Kandidat", UniversityID = "KU", Id = 110 },
                    new Education { Name = "Cand.merc. International Business and Management", Grade = "Kandidat", UniversityID = "SDU", Id = 111 },
                    new Education { Name = "Samfundsfag", Grade = "Kandidat", UniversityID = "KU", Id = 112 },
                    new Education { Name = "Farmaceutisk videnskab", Grade = "Kandidat", UniversityID = "KU", Id = 113 },
                    new Education { Name = "Medicin", Grade = "Bachelor", UniversityID = "KU", Id = 114 },
                    new Education { Name = "Civilingeniør i Miljøteknologi", Grade = "Kandidat", UniversityID = "SDU", Id = 115 },
                    new Education { Name = "Environmental and Resource Management", Grade = "Kandidat", UniversityID = "SDU", Id = 116 },
                    new Education { Name = "Retorik", Grade = "Bachelor", UniversityID = "KU", Id = 117 },
                    new Education { Name = "Diplomingeniør i Maskinteknik", Grade = "Bachelor", UniversityID = "SDU", Id = 118 },
                    new Education { Name = "HA i markeds- og kulturanalyse", Grade = "Bachelor", UniversityID = "CBS", Id = 119 },
                    new Education { Name = "Sundhedsfaglig kandidatuddannelse (kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 120 },
                    new Education { Name = "Business Administration and Information Systems", Grade = "Kandidat", UniversityID = "CBS", Id = 121 },
                    new Education { Name = "Fysik", Grade = "Bachelor", UniversityID = "SDU", Id = 122 },
                    new Education { Name = "Historie", Grade = "Bachelor", UniversityID = "KU", Id = 123 },
                    new Education { Name = "HA(it.)", Grade = "Bachelor", UniversityID = "CBS", Id = 124 },
                    new Education { Name = "Miljø- og fødevareøkonomi", Grade = "Bachelor", UniversityID = "KU", Id = 125 },
                    new Education { Name = "Religionsvidenskab", Grade = "Bachelor", UniversityID = "KU", Id = 126 },
                    new Education { Name = "Litteraturvidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 127 },
                    new Education { Name = "Latin", Grade = "Bachelor", UniversityID = "KU", Id = 128 },
                    new Education { Name = "Naturforvaltning", Grade = "Kandidat", UniversityID = "KU", Id = 129 },
                    new Education { Name = "HA(jur.)", Grade = "Bachelor", UniversityID = "CBS", Id = 130 },
                    new Education { Name = "Bibliotekskundskab og videnskommunikation", Grade = "Bachelor", UniversityID = "SDU", Id = 131 },
                    new Education { Name = "Humanfysiologi", Grade = "Kandidat", UniversityID = "KU", Id = 132 },
                    new Education { Name = "Religionsstudier (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 133 },
                    new Education { Name = "Digital Innovation & Management", Grade = "Kandidat", UniversityID = "ITU", Id = 134 },
                    new Education { Name = "Jordemodervidenskab (kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 135 },
                    new Education { Name = "Landskabsarkitektur", Grade = "Kandidat", UniversityID = "KU", Id = 136 },
                    new Education { Name = "Statskundskab", Grade = "Bachelor", UniversityID = "KU", Id = 137 },
                    new Education { Name = "Litteraturvidenskab (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 138 },
                    new Education { Name = "Cand.merc. Sports and Event Management", Grade = "Kandidat", UniversityID = "SDU", Id = 139 },
                    new Education { Name = "Oldtidskundskab", Grade = "Bachelor", UniversityID = "SDU", Id = 140 },
                    new Education { Name = "Erhvervsøkonomi - Finansiering og Regnskab", Grade = "Kandidat", UniversityID = "CBS", Id = 141 },
                    new Education { Name = "Immunologi og inflammation", Grade = "Kandidat", UniversityID = "KU", Id = 142 },
                    new Education { Name = "Fødevareinnovation og sundhed", Grade = "Kandidat", UniversityID = "KU", Id = 143 },
                    new Education { Name = "Biologi", Grade = "Bachelor", UniversityID = "KU", Id = 144 },
                    new Education { Name = "Fysik", Grade = "Kandidat", UniversityID = "KU", Id = 145 },
                    new Education { Name = "Samfundsfag", Grade = "Bachelor", UniversityID = "KU", Id = 146 },
                    new Education { Name = "Business Administration and Philosophy", Grade = "Kandidat", UniversityID = "CBS", Id = 147 },
                    new Education { Name = "Erhvervsøkonomi - Finance and Strategic Management", Grade = "Kandidat", UniversityID = "CBS", Id = 148 },
                    new Education { Name = "Diplomingeniør i robotteknologi", Grade = "Bachelor", UniversityID = "SDU", Id = 149 },
                    new Education { Name = "Data Science", Grade = "Bachelor", UniversityID = "ITU", Id = 150 },
                    new Education { Name = "Pædagogik", Grade = "Kandidat", UniversityID = "KU", Id = 151 },
                    new Education { Name = "Odontologi", Grade = "Kandidat", UniversityID = "KU", Id = 152 },
                    new Education { Name = "Machine learning og datavidenskab", Grade = "Bachelor", UniversityID = "KU", Id = 153 },
                    new Education { Name = "Kunsthistorie", Grade = "Bachelor", UniversityID = "KU", Id = 154 },
                    new Education { Name = "Civilingeniør i fysik og teknologi", Grade = "Bachelor", UniversityID = "SDU", Id = 155 },
                    new Education { Name = "Geologi - geoscience", Grade = "Kandidat", UniversityID = "KU", Id = 156 },
                    new Education { Name = "Datalogi", Grade = "Kandidat", UniversityID = "KU", Id = 157 },
                    new Education { Name = "Designkultur", Grade = "Bachelor", UniversityID = "SDU", Id = 158 },
                    new Education { Name = "Migrationsstudier", Grade = "Kandidat", UniversityID = "KU", Id = 159 },
                    new Education { Name = "Erhvervsøkonomi - Accounting, Strategy and Control", Grade = "Kandidat", UniversityID = "CBS", Id = 160 },
                    new Education { Name = "Erhvervsøkonomi - Sales Management", Grade = "Kandidat", UniversityID = "CBS", Id = 161 },
                    new Education { Name = "Cand.merc. Entreprenørskab og ledelse", Grade = "Kandidat", UniversityID = "SDU", Id = 162 },
                    new Education { Name = "Interkulturelle markedsstudier", Grade = "Kandidat", UniversityID = "KU", Id = 163 },
                    new Education { Name = "Business, Language & Culture", Grade = "Bachelor", UniversityID = "CBS", Id = 164 },
                    new Education { Name = "Sprogpsykologi", Grade = "Kandidat", UniversityID = "KU", Id = 165 },
                    new Education { Name = "Human ernæring", Grade = "Kandidat", UniversityID = "KU", Id = 166 },
                    new Education { Name = "Matematik", Grade = "Kandidat", UniversityID = "KU", Id = 167 },
                    new Education { Name = "Landskabsarkitektur", Grade = "Bachelor", UniversityID = "KU", Id = 168 },
                    new Education { Name = "Erhvervsøkonomi, HA", Grade = "Bachelor", UniversityID = "SDU", Id = 169 },
                    new Education { Name = "Digital Design and Interactive Technologies", Grade = "Bachelor", UniversityID = "ITU", Id = 170 },
                    new Education { Name = "International Business", Grade = "Bachelor", UniversityID = "CBS", Id = 171 },
                    new Education { Name = "Cand.merc. Management Accounting", Grade = "Kandidat", UniversityID = "SDU", Id = 172 },
                    new Education { Name = "Civilingeniør i Product Development and Innovation", Grade = "Kandidat", UniversityID = "SDU", Id = 173 },
                    new Education { Name = "Idræt og sundhed", Grade = "Bachelor", UniversityID = "SDU", Id = 174 },
                    new Education { Name = "Mellemøststudier (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 175 },
                    new Education { Name = "Filosofi", Grade = "Kandidat", UniversityID = "KU", Id = 176 },
                    new Education { Name = "Civilingeniør i Mechatronics", Grade = "Kandidat", UniversityID = "SDU", Id = 177 },
                    new Education { Name = "Erhvervsøkonomi og Psykologi", Grade = "Kandidat", UniversityID = "CBS", Id = 178 },
                    new Education { Name = "Musikvidenskab", Grade = "Bachelor", UniversityID = "KU", Id = 179 },
                    new Education { Name = "Dansk", Grade = "Kandidat", UniversityID = "KU", Id = 180 },
                    new Education { Name = "Informationsstudier", Grade = "Bachelor", UniversityID = "KU", Id = 181 },
                    new Education { Name = "Erhvervsøkonomi-erhvervssprog (negot) i international turisme og fritidsmanagement", Grade = "Kandidat", UniversityID = "SDU", Id = 182 },
                    new Education { Name = "Global udvikling", Grade = "Kandidat", UniversityID = "KU", Id = 183 },
                    new Education { Name = "International Security and Law", Grade = "Kandidat", UniversityID = "SDU", Id = 184 },
                    new Education { Name = "Fødevarer og ernæring", Grade = "Bachelor", UniversityID = "KU", Id = 185 },
                    new Education { Name = "Geologi - geoscience", Grade = "Bachelor", UniversityID = "KU", Id = 186 },
                    new Education { Name = "Farmaci", Grade = "Bachelor", UniversityID = "KU", Id = 187 },
                    new Education { Name = "Cand.merc. Styring og Ledelse", Grade = "Kandidat", UniversityID = "SDU", Id = 188 },
                    new Education { Name = "Kultur og formidling (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 189 },
                    new Education { Name = "Journalistik (cand.mag.)", Grade = "Kandidat", UniversityID = "SDU", Id = 190 },
                    new Education { Name = "Historie", Grade = "Kandidat", UniversityID = "KU", Id = 191 },
                    new Education { Name = "Psykologi (kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 192 },
                    new Education { Name = "Medicinalkemi", Grade = "Bachelor", UniversityID = "KU", Id = 193 },
                    new Education { Name = "Uddannelsesnavn", Grade = "Grad", UniversityID = "Uni abbrv", Id = 194 },
                    new Education { Name = "Civilingeniør i Spiludvikling og læringsteknologi", Grade = "Kandidat", UniversityID = "SDU", Id = 195 },
                    new Education { Name = "Historie", Grade = "Bachelor", UniversityID = "SDU", Id = 196 },
                    new Education { Name = "Religionsstudier", Grade = "Bachelor", UniversityID = "SDU", Id = 197 },
                    new Education { Name = "Jura", Grade = "Kandidat", UniversityID = "KU", Id = 198 },
                    new Education { Name = "Folkesundhedsvidenskab", Grade = "Bachelor", UniversityID = "SDU", Id = 199 },
                    new Education { Name = "Husdyrvidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 200 },
                    new Education { Name = "Civilingeniør i Mechatronics", Grade = "Bachelor", UniversityID = "SDU", Id = 201 },
                    new Education { Name = "Civilingeniør i Software Engineering", Grade = "Kandidat", UniversityID = "SDU", Id = 202 },
                    new Education { Name = "Business Administration and Ebusiness", Grade = "Kandidat", UniversityID = "CBS", Id = 203 },
                    new Education { Name = "Civilingeniør i Sundheds- og Velfærdsteknologi", Grade = "Kandidat", UniversityID = "SDU", Id = 204 },
                    new Education { Name = "Advanced Economics and Finance (cand.oecon.)", Grade = "Kandidat", UniversityID = "CBS", Id = 205 },
                    new Education { Name = "Erhvervsøkonomi - Management of Innovation and Business Development", Grade = "Kandidat", UniversityID = "CBS", Id = 206 },
                    new Education { Name = "Naturressourcer", Grade = "Bachelor", UniversityID = "KU", Id = 207 },
                    new Education { Name = "Cand.merc.jur. (Erhvervsjura)", Grade = "Kandidat", UniversityID = "SDU", Id = 208 },
                    new Education { Name = "Assyriologi", Grade = "Kandidat", UniversityID = "KU", Id = 209 },
                    new Education { Name = "Indianske sprog og kulturer", Grade = "Bachelor", UniversityID = "KU", Id = 210 },
                    new Education { Name = "Sociologi", Grade = "Kandidat", UniversityID = "KU", Id = 211 },
                    new Education { Name = "Erhvervsøkonomi og jura, HA (jur.)", Grade = "Bachelor", UniversityID = "SDU", Id = 212 },
                    new Education { Name = "European Master in Tourism Management", Grade = "Kandidat", UniversityID = "SDU", Id = 213 },
                    new Education { Name = "Diplomingeniør i Electronics", Grade = "Bachelor", UniversityID = "SDU", Id = 214 },
                    new Education { Name = "Erhvervsøkonomi-erhvervssprog (negot)", Grade = "Bachelor", UniversityID = "SDU", Id = 215 },
                    new Education { Name = "Cand.merc. Global Marketing and Consumer Culture", Grade = "Kandidat", UniversityID = "SDU", Id = 216 },
                    new Education { Name = "Asienstudier", Grade = "Kandidat", UniversityID = "KU", Id = 217 },
                    new Education { Name = "Økonomi (cand.oecon.)", Grade = "Kandidat", UniversityID = "SDU", Id = 218 },
                    new Education { Name = "HA i europæisk business", Grade = "Bachelor", UniversityID = "CBS", Id = 219 },
                    new Education { Name = "Biomedicin", Grade = "Kandidat", UniversityID = "SDU", Id = 220 },
                    new Education { Name = "Nærorientalsk arkæologi", Grade = "Kandidat", UniversityID = "KU", Id = 221 },
                    new Education { Name = "Antropologi", Grade = "Kandidat", UniversityID = "KU", Id = 222 },
                    new Education { Name = "Erhvervsøkonomi - People and Business Development", Grade = "Kandidat", UniversityID = "CBS", Id = 223 },
                    new Education { Name = "Civilingeniør i Robotteknologi (Avanceret robotteknologi/Droner og autonome systemer)", Grade = "Kandidat", UniversityID = "SDU", Id = 224 },
                    new Education { Name = "Journalistik (cand.public.)", Grade = "Kandidat", UniversityID = "SDU", Id = 225 },
                    new Education { Name = "Molekylær biomedicin", Grade = "Kandidat", UniversityID = "KU", Id = 226 },
                    new Education { Name = "Idræt og fysisk aktivitet", Grade = "Bachelor", UniversityID = "KU", Id = 227 },
                    new Education { Name = "Journalistik", Grade = "Bachelor", UniversityID = "SDU", Id = 228 },
                    new Education { Name = "Amerikanske studier", Grade = "Bachelor", UniversityID = "SDU", Id = 229 },
                    new Education { Name = "Jura", Grade = "Bachelor", UniversityID = "KU", Id = 230 },
                    new Education { Name = "Organisational Innovation and Entrepreneurship (cand.soc.)", Grade = "Kandidat", UniversityID = "CBS", Id = 231 },
                    new Education { Name = "Diplomingeniør i elektronik", Grade = "Bachelor", UniversityID = "SDU", Id = 232 },
                    new Education { Name = "Digital Design and Interactive Technologies", Grade = "Kandidat", UniversityID = "ITU", Id = 233 },
                    new Education { Name = "Civilingeniør i kemi og bioteknologi", Grade = "Bachelor", UniversityID = "SDU", Id = 234 },
                    new Education { Name = "Økonomi (oecon.)", Grade = "Bachelor", UniversityID = "SDU", Id = 235 },
                    new Education { Name = "Civilingeniør i Operations Management", Grade = "Kandidat", UniversityID = "SDU", Id = 236 },
                    new Education { Name = "International virksomhedskommunikation - 2 fremmedsprog", Grade = "Bachelor", UniversityID = "SDU", Id = 237 },
                    new Education { Name = "Økonomi", Grade = "Kandidat", UniversityID = "KU", Id = 238 },
                    new Education { Name = "Ergoterapi (kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 239 },
                    new Education { Name = "Matematik", Grade = "Kandidat", UniversityID = "SDU", Id = 240 },
                    new Education { Name = "Kemi", Grade = "Kandidat", UniversityID = "KU", Id = 241 },
                    new Education { Name = "Cand.merc.aud. (Revisor)", Grade = "Kandidat", UniversityID = "SDU", Id = 242 },
                    new Education { Name = "Portugisiske og brasilianske studier", Grade = "Kandidat", UniversityID = "KU", Id = 243 },
                    new Education { Name = "Sundhedsfaglig kandidatuddannelse", Grade = "Kandidat", UniversityID = "KU", Id = 244 },
                    new Education { Name = "International Business in Asia - Chinese", Grade = "Bachelor", UniversityID = "CBS", Id = 245 },
                    new Education { Name = "Sociologi", Grade = "Bachelor", UniversityID = "KU", Id = 246 },
                    new Education { Name = "Global sundhed", Grade = "Kandidat", UniversityID = "KU", Id = 247 },
                    new Education { Name = "Cand.merc.int., Sønderborg", Grade = "Kandidat", UniversityID = "SDU", Id = 248 },
                    new Education { Name = "Filosofi (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 249 },
                    new Education { Name = "Interreligiøse islamstudier", Grade = "Kandidat", UniversityID = "KU", Id = 250 },
                    new Education { Name = "Forsikringsmatematik", Grade = "Kandidat", UniversityID = "KU", Id = 251 },
                    new Education { Name = "Medievidenskab", Grade = "Bachelor", UniversityID = "SDU", Id = 252 },
                    new Education { Name = "Biomedicinsk informatik", Grade = "Kandidat", UniversityID = "SDU", Id = 253 },
                    new Education { Name = "Biomedicin", Grade = "Bachelor", UniversityID = "SDU", Id = 254 },
                    new Education { Name = "Farmaci", Grade = "Kandidat", UniversityID = "KU", Id = 255 },
                    new Education { Name = "Antropologi", Grade = "Bachelor", UniversityID = "KU", Id = 256 },
                    new Education { Name = "Human Resource Management", Grade = "Kandidat", UniversityID = "CBS", Id = 257 },
                    new Education { Name = "International virksomhedskommunikation - Tysk", Grade = "Bachelor", UniversityID = "SDU", Id = 258 }, new Education { Name = "Cand.merc. Business Controlling", Grade = "Kandidat", UniversityID = "SDU", Id = 259 },
                    new Education { Name = "Tandplejeruddannelsen", Grade = "Bachelor", UniversityID = "KU", Id = 260 },
                    new Education { Name = "Business Administration and Innovation in Health Care", Grade = "Kandidat", UniversityID = "CBS", Id = 261 },
                    new Education { Name = "Molekylær biomedicin", Grade = "Bachelor", UniversityID = "KU", Id = 262 },
                    new Education { Name = "Cand.merc. Brand Management and Marketing Communication", Grade = "Kandidat", UniversityID = "SDU", Id = 263 },
                    new Education { Name = "Medicinalkemi", Grade = "Kandidat", UniversityID = "KU", Id = 264 },
                    new Education { Name = "Geografi og geoinformatik", Grade = "Bachelor", UniversityID = "KU", Id = 265 },
                    new Education { Name = "Civilingeniør i Innovation and Business", Grade = "Bachelor", UniversityID = "SDU", Id = 266 },
                    new Education { Name = "Statskundskab", Grade = "Kandidat", UniversityID = "SDU", Id = 267 },
                    new Education { Name = "Farmaci", Grade = "Bachelor", UniversityID = "SDU", Id = 268 },
                    new Education { Name = "Odontologi", Grade = "Bachelor", UniversityID = "KU", Id = 269 },
                    new Education { Name = "Biokemi og molekylær biologi", Grade = "Bachelor", UniversityID = "SDU", Id = 270 },
                    new Education { Name = "Sundhed og informatik", Grade = "Bachelor", UniversityID = "KU", Id = 271 },
                    new Education { Name = "Engelsk", Grade = "Bachelor", UniversityID = "KU", Id = 272 },
                    new Education { Name = "Business Administration & Digital Management", Grade = "Bachelor", UniversityID = "CBS", Id = 273 },
                    new Education { Name = "Datalogi", Grade = "Bachelor", UniversityID = "KU", Id = 274 },
                    new Education { Name = "Diplomingeniør i kemi- og bioteknologi", Grade = "Bachelor", UniversityID = "SDU", Id = 275 },
                    new Education { Name = "Cand.merc. Human Resource Management", Grade = "Kandidat", UniversityID = "SDU", Id = 276 },
                    new Education { Name = "Religionsvidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 277 },
                    new Education { Name = "Mellemøstens sprog og samfund", Grade = "Bachelor", UniversityID = "KU", Id = 278 },
                    new Education { Name = "Business Administration & Sociology", Grade = "Bachelor", UniversityID = "CBS", Id = 279 },
                    new Education { Name = "Asienstudier (kinastudier)", Grade = "Bachelor", UniversityID = "KU", Id = 280 },
                    new Education { Name = "Forsikringsmatematik", Grade = "Bachelor", UniversityID = "KU", Id = 281 },
                    new Education { Name = "Samfundsfag", Grade = "Kandidat", UniversityID = "SDU", Id = 282 },
                    new Education { Name = "Bioinformatik", Grade = "Kandidat", UniversityID = "KU", Id = 283 },
                    new Education { Name = "Klinisk sygepleje (kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 284 },
                    new Education { Name = "Psykologi", Grade = "Bachelor", UniversityID = "KU", Id = 285 },
                    new Education { Name = "Medicin", Grade = "Bachelor", UniversityID = "SDU", Id = 286 },
                    new Education { Name = "Europæisk etnologi", Grade = "Kandidat", UniversityID = "KU", Id = 287 },
                    new Education { Name = "Grønlandske og arktiske studier", Grade = "Kandidat", UniversityID = "KU", Id = 288 },
                    new Education { Name = "Klassisk arkæologi", Grade = "Kandidat", UniversityID = "KU", Id = 289 },
                    new Education { Name = "Østeuropastudier", Grade = "Kandidat", UniversityID = "KU", Id = 290 },
                    new Education { Name = "Forhistorisk arkæologi", Grade = "Kandidat", UniversityID = "KU", Id = 291 },
                    new Education { Name = "Designledelse", Grade = "Kandidat", UniversityID = "SDU", Id = 292 },
                    new Education { Name = "Filosofi", Grade = "Bachelor", UniversityID = "KU", Id = 293 },
                    new Education { Name = "Lingvistik", Grade = "Bachelor", UniversityID = "KU", Id = 294 },
                    new Education { Name = "Dansk", Grade = "Bachelor", UniversityID = "KU", Id = 295 },
                    new Education { Name = "Afrikastudier", Grade = "Kandidat", UniversityID = "KU", Id = 296 },
                    new Education { Name = "Statskundskab", Grade = "Bachelor", UniversityID = "SDU", Id = 297 },
                    new Education { Name = "Sikkerheds- og risikoledelse", Grade = "Kandidat", UniversityID = "KU", Id = 298 },
                    new Education { Name = "Moderne kultur", Grade = "Kandidat", UniversityID = "KU", Id = 299 },
                    new Education { Name = "Historie (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 300 },
                    new Education { Name = "HA almen", Grade = "Bachelor", UniversityID = "CBS", Id = 301 },
                    new Education { Name = "International Shipping & Trade", Grade = "Bachelor", UniversityID = "CBS", Id = 302 },
                    new Education { Name = "Klassisk græsk", Grade = "Bachelor", UniversityID = "KU", Id = 303 },
                    new Education { Name = "Cand. it. - Product Design", Grade = "Kandidat", UniversityID = "SDU", Id = 304 },
                    new Education { Name = "Erhvervsøkonomi - Supply Chain Management", Grade = "Kandidat", UniversityID = "CBS", Id = 305 },
                    new Education { Name = "Teologi", Grade = "Bachelor", UniversityID = "KU", Id = 306 },
                    new Education { Name = "Retorik", Grade = "Kandidat", UniversityID = "KU", Id = 307 },
                    new Education { Name = "Ægyptologi", Grade = "Kandidat", UniversityID = "KU", Id = 308 },
                    new Education { Name = "Biologi", Grade = "Bachelor", UniversityID = "SDU", Id = 309 },
                    new Education { Name = "Fysik", Grade = "Kandidat", UniversityID = "SDU", Id = 310 },
                    new Education { Name = "Naturressourcer og udvikling", Grade = "Kandidat", UniversityID = "KU", Id = 311 },
                    new Education { Name = "Lægemiddelvidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 312 },
                    new Education { Name = "Skov- og landskabsingeniørvirksomhed", Grade = "Bachelor", UniversityID = "KU", Id = 313 },
                    new Education { Name = "Samfundsfag", Grade = "Bachelor", UniversityID = "SDU", Id = 314 },
                    new Education { Name = "Klimaforandringer", Grade = "Kandidat", UniversityID = "KU", Id = 315 },
                    new Education { Name = "Audiologopædi", Grade = "Kandidat", UniversityID = "KU", Id = 316 },
                    new Education { Name = "Grønlandske og arktiske studier", Grade = "Bachelor", UniversityID = "KU", Id = 317 },
                    new Education { Name = "Klassisk arkæologi", Grade = "Bachelor", UniversityID = "KU", Id = 318 },
                    new Education { Name = "Forhistorisk arkæologi", Grade = "Bachelor", UniversityID = "KU", Id = 319 },
                    new Education { Name = "Designkultur og økonomi", Grade = "Bachelor", UniversityID = "SDU", Id = 320 },
                    new Education { Name = "Audiologi", Grade = "Bachelor", UniversityID = "SDU", Id = 321 },
                    new Education { Name = "Matematik-økonomi", Grade = "Kandidat", UniversityID = "KU", Id = 322 },
                    new Education { Name = "Matematik og Anvendt matematik", Grade = "Bachelor", UniversityID = "SDU", Id = 323 },
                    new Education { Name = "Italiensk sprog og kultur", Grade = "Bachelor", UniversityID = "KU", Id = 324 },
                    new Education { Name = "Agronomi", Grade = "Kandidat", UniversityID = "KU", Id = 325 },
                    new Education { Name = "Kommunikation og it", Grade = "Bachelor", UniversityID = "KU", Id = 326 },
                    new Education { Name = "European Studies", Grade = "Bachelor", UniversityID = "SDU", Id = 327 },
                    new Education { Name = "Audiologi (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 328 },
                    new Education { Name = "Husdyrvidenskab", Grade = "Bachelor", UniversityID = "KU", Id = 329 },
                    new Education { Name = "Datalogi", Grade = "Kandidat", UniversityID = "SDU", Id = 330 },
                    new Education { Name = "Dansk (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 331 },
                    new Education { Name = "Civilingeniør i Software Engineering", Grade = "Bachelor", UniversityID = "SDU", Id = 332 },
                    new Education { Name = "Erhvervsøkonomi og Virksomhedskommunikation", Grade = "Kandidat", UniversityID = "CBS", Id = 333 },
                    new Education { Name = "Erhvervsøkonomi - Økonomisk Markedsføring", Grade = "Kandidat", UniversityID = "CBS", Id = 334 },
                    new Education { Name = "Jordbrugsøkonomi", Grade = "Kandidat", UniversityID = "KU", Id = 335 },
                    new Education { Name = "Folkesundhedsvidenskab (kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 336 },
                    new Education { Name = "Civilingeniør i robotteknologi", Grade = "Bachelor", UniversityID = "SDU", Id = 337 },
                    new Education { Name = "HA(psyk.)", Grade = "Bachelor", UniversityID = "CBS", Id = 338 },
                    new Education { Name = "Global Business Informatics", Grade = "Bachelor", UniversityID = "ITU", Id = 339 },
                    new Education { Name = "Miljøvidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 340 },
                    new Education { Name = "Biologi", Grade = "Kandidat", UniversityID = "KU", Id = 341 },
                    new Education { Name = "Management of Creative Business Processes (cand.soc.)", Grade = "Kandidat", UniversityID = "CBS", Id = 342 },
                    new Education { Name = "Litteraturvidenskab", Grade = "Bachelor", UniversityID = "KU", Id = 343 },
                    new Education { Name = "Musikvidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 344 },
                    new Education { Name = "Teater- og performancestudier", Grade = "Kandidat", UniversityID = "KU", Id = 345 },
                    new Education { Name = "Computer Science", Grade = "Kandidat", UniversityID = "ITU", Id = 346 },
                    new Education { Name = "Pædagogik (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 347 },
                    new Education { Name = "Mellemøstens sprog og samfund (nærorientalsk ark.)", Grade = "Bachelor", UniversityID = "KU", Id = 348 },
                    new Education { Name = "Sundhed og informatik", Grade = "Kandidat", UniversityID = "KU", Id = 349 },
                    new Education { Name = "Sociologi og kulturanalyse", Grade = "Bachelor", UniversityID = "SDU", Id = 350 },
                    new Education { Name = "Europas religiøse rødder", Grade = "Kandidat", UniversityID = "KU", Id = 351 },
                    new Education { Name = "It og kognition", Grade = "Kandidat", UniversityID = "KU", Id = 352 },
                    new Education { Name = "Kunsthistorie", Grade = "Kandidat", UniversityID = "KU", Id = 353 },
                    new Education { Name = "Audiologopædi", Grade = "Bachelor", UniversityID = "KU", Id = 354 },
                    new Education { Name = "Fysioterapi (kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 355 },
                    new Education { Name = "Software Development", Grade = "Bachelor", UniversityID = "ITU", Id = 356 },
                    new Education { Name = "Klassiske studier: Oldtidskundskab (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 357 }, new Education { Name = "Erhvervsøkonomi-erhvervssprog (negot) - engelsk eller tysk (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 358 },
                    new Education { Name = "Informationsvidenskab og kulturformidling", Grade = "Kandidat", UniversityID = "KU", Id = 359 },
                    new Education { Name = "Fødevarevidenskab/mejeriingeniør", Grade = "Kandidat", UniversityID = "KU", Id = 360 },
                    new Education { Name = "Diplomingeniør i bygningsteknik", Grade = "Bachelor", UniversityID = "SDU", Id = 361 },
                    new Education { Name = "Mellemøstens sprog og samfund (assyriologi)", Grade = "Bachelor", UniversityID = "KU", Id = 362 },
                    new Education { Name = "International virksomhedskommunikation - Engelsk", Grade = "Bachelor", UniversityID = "SDU", Id = 363 },
                    new Education { Name = "Stem-undervisning", Grade = "Kandidat", UniversityID = "KU", Id = 364 },
                    new Education { Name = "Civilingeniør i Electronics", Grade = "Kandidat", UniversityID = "SDU", Id = 365 },
                    new Education { Name = "Kemi", Grade = "Bachelor", UniversityID = "KU", Id = 366 },
                    new Education { Name = "Datalogi", Grade = "Bachelor", UniversityID = "SDU", Id = 367 },
                    new Education { Name = "Fysik", Grade = "Bachelor", UniversityID = "KU", Id = 368 },
                    new Education { Name = "Økonomi", Grade = "Bachelor", UniversityID = "KU", Id = 369 },
                    new Education { Name = "Cand.merc. Forretnings- & Markedsudvikling", Grade = "Kandidat", UniversityID = "SDU", Id = 370 },
                    new Education { Name = "Diplomingeniør i softwareteknologi", Grade = "Bachelor", UniversityID = "SDU", Id = 371 },
                    new Education { Name = "Pædagogik", Grade = "Bachelor", UniversityID = "KU", Id = 372 },
                    new Education { Name = "Cand.soc. i jura", Grade = "Kandidat", UniversityID = "KU", Id = 373 },
                    new Education { Name = "Cand.merc. Strategy and Organization", Grade = "Kandidat", UniversityID = "SDU", Id = 374 },
                    new Education { Name = "Film- og medievidenskab", Grade = "Kandidat", UniversityID = "KU", Id = 375 },
                    new Education { Name = "Civilingeniør i Maskinteknik", Grade = "Bachelor", UniversityID = "SDU", Id = 376 },
                    new Education { Name = "Neuroscience", Grade = "Kandidat", UniversityID = "KU", Id = 377 },
                    new Education { Name = "Erhvervsøkonomi - International Marketing and Management", Grade = "Kandidat", UniversityID = "CBS", Id = 378 },
                    new Education { Name = "Bioteknologi", Grade = "Kandidat", UniversityID = "KU", Id = 379 },
                    new Education { Name = "Cand.merc. International Business and Marketing", Grade = "Kandidat", UniversityID = "SDU", Id = 380 },
                    new Education { Name = "Civilingeniør i spiludvikling og læringsteknologi", Grade = "Bachelor", UniversityID = "SDU", Id = 381 },
                    new Education { Name = "Jura", Grade = "Kandidat", UniversityID = "SDU", Id = 382 },
                    new Education { Name = "Fransk sprog og kultur", Grade = "Kandidat", UniversityID = "KU", Id = 383 },
                    new Education { Name = "Filosofi", Grade = "Bachelor", UniversityID = "SDU", Id = 384 },
                    new Education { Name = "Matematik", Grade = "Bachelor", UniversityID = "KU", Id = 385 },
                    new Education { Name = "Diplomingeniør i Mechatronics", Grade = "Bachelor", UniversityID = "SDU", Id = 386 },
                    new Education { Name = "Klinisk ernæring", Grade = "Kandidat", UniversityID = "KU", Id = 387 },
                    new Education { Name = "Dansk", Grade = "Bachelor", UniversityID = "SDU", Id = 388 },
                    new Education { Name = "Integrerede fødevarestudier", Grade = "Kandidat", UniversityID = "KU", Id = 389 },
                    new Education { Name = "International erhvervsøkonomi med fremmedsprog (BA int.)", Grade = "Bachelor", UniversityID = "SDU", Id = 390 },
                    new Education { Name = "Civilingeniør i Konstruktionsteknik", Grade = "Kandidat", UniversityID = "SDU", Id = 391 },
                    new Education { Name = "Tysk (Kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 392 },
                    new Education { Name = "International Business in Asia - Japanese", Grade = "Bachelor", UniversityID = "CBS", Id = 393 },
                    new Education { Name = "Civilingeniør i Kemi og bioteknologi (kandidat)", Grade = "Kandidat", UniversityID = "SDU", Id = 394 },
                    new Education { Name = "Datalogi-økonomi", Grade = "Bachelor", UniversityID = "KU", Id = 395 },
                    new Education { Name = "Civilingeniør i Sundheds- og velfærdsteknologi", Grade = "Bachelor", UniversityID = "SDU", Id = 396 },
                    new Education { Name = "Audiologopædi", Grade = "Kandidat", UniversityID = "SDU", Id = 397 },
                    new Education { Name = "Bioteknologi", Grade = "Bachelor", UniversityID = "KU", Id = 398 },
                    new Education { Name = "Kognition og kommunikation", Grade = "Kandidat", UniversityID = "KU", Id = 399 },
                    new Education { Name = "Europæisk etnologi", Grade = "Bachelor", UniversityID = "KU", Id = 400 },
                    new Education { Name = "Tysk sprog og kultur", Grade = "Kandidat", UniversityID = "KU", Id = 401 },
                    new Education { Name = "Østeuropastudier", Grade = "Bachelor", UniversityID = "KU", Id = 402 },
                    new Education { Name = "Jura", Grade = "Bachelor", UniversityID = "SDU", Id = 403 },
                    new Education { Name = "Cand.merc. Accounting and Finance", Grade = "Kandidat", UniversityID = "SDU", Id = 404 },
                    new Education { Name = "Moderne indien og sydasienstudier", Grade = "Bachelor", UniversityID = "KU", Id = 405 },
                    new Education { Name = "Spansk sprog og kultur", Grade = "Kandidat", UniversityID = "KU", Id = 406 }
                );
        }
    }
}
