global using System;
global using Microsoft.Data.Sqlite;
global using Microsoft.EntityFrameworkCore;
global using Xunit;
global using System.Collections.Generic;
global using System.Threading.Tasks;
global using System.Linq;
global using Core;
global using PBInfrastructure;
global using Xunit;
global using System.Collections.Generic;
global using Microsoft.EntityFrameworkCore;
global using System.Linq;
global using PB.Core;
global using Core;
global using static PB.Core.University;
global using static PB.Core.Response;
